server:
  port: ${PORT:8080}


spring:
  application:
    name: tripmate-backend

  datasource:
    url: ${DB_URL:jdbc:h2:mem:tripmatedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:sa}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}



  jackson:
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250655368566D5971}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}

